export const ALL_APP_DRAW_TYPES: JAPP_DRAW_TYPES[] = [
  JAPP_DRAW_TYPES.POINT,
  JAPP_DRAW_TYPES.POLYGON,
  JAPP_DRAW_TYPES.LINE_STRING,
  JAPP_DRAW_TYPES.RECTANGLE,
  JAPP_DRAW_TYPES.CIRCLE,
  JAPP_DRAW_TYPES.TEXT
]

export const ALL_APP_MEASUREMENT_SYSTEMS: JAPP_MEASUREMENT_SYSTEMS[] = [
  JAPP_MEASUREMENT_SYSTEMS.GEODETIC,
  JAPP_MEASUREMENT_SYSTEMS.PLANAR
]

export const ALL_APP_DRAW_MODES: JAPP_DRAW_MODES[] = [
  JAPP_DRAW_MODES.DRAW,
  JAPP_DRAW_MODES.SELECT,
  JAPP_DRAW_MODES.DELETE
]

export const ALL_APP_GEOMETRY_WIZARD_STEPS: JAPP_GEOMETRY_WIZARD_STEPS[] = [
  JAPP_GEOMETRY_WIZARD_STEPS.SELECT_LAYER,
  JAPP_GEOMETRY_WIZARD_STEPS.DRAW
]

export const ALL_APP_LAYER_DATE_FILTER_OPERATOR_TYPES: JAPP_LAYER_DATE_FILTER_OPERATOR_TYPES[] = [
  JAPP_LAYER_DATE_FILTER_OPERATOR_TYPES.BEFORE,
  JAPP_LAYER_DATE_FILTER_OPERATOR_TYPES.AFTER,
  JAPP_LAYER_DATE_FILTER_OPERATOR_TYPES.BETWEEN,
  JAPP_LAYER_DATE_FILTER_OPERATOR_TYPES.LAST_PERIOD
]

export const ALL_APP_LAYER_TEXT_FILTER_OPERATOR_TYPES: JAPP_LAYER_TEXT_FILTER_OPERATOR_TYPES[] = [
  JAPP_LAYER_TEXT_FILTER_OPERATOR_TYPES.CONTAINS,
  JAPP_LAYER_TEXT_FILTER_OPERATOR_TYPES.DOES_NOT_CONTAIN,
  JAPP_LAYER_TEXT_FILTER_OPERATOR_TYPES.EQUALS,
  JAPP_LAYER_TEXT_FILTER_OPERATOR_TYPES.DOES_NOT_EQUALS
]

export const ALL_APP_LAYER_NUMBER_FILTER_OPERATOR_TYPES: JAPP_LAYER_NUMBER_FILTER_OPERATOR_TYPES[] = [
  JAPP_LAYER_NUMBER_FILTER_OPERATOR_TYPES.EQUALS,
  JAPP_LAYER_NUMBER_FILTER_OPERATOR_TYPES.DOES_NOT_EQUALS,
  JAPP_LAYER_NUMBER_FILTER_OPERATOR_TYPES.SMALLER_THAN,
  JAPP_LAYER_NUMBER_FILTER_OPERATOR_TYPES.GREATER_THAN
]

export const ALL_APP_LAYER_FILTER_DATE_PERIOD_TYPES: JAPP_LAYER_FILTER_DATE_PERIOD_TYPES[] = [
  JAPP_LAYER_FILTER_DATE_PERIOD_TYPES.DAY,
  JAPP_LAYER_FILTER_DATE_PERIOD_TYPES.WEEK,
  JAPP_LAYER_FILTER_DATE_PERIOD_TYPES.MONTH,
  JAPP_LAYER_FILTER_DATE_PERIOD_TYPES.YEAR
]

export const ALL_APP_LAYER_EDITION_TABS: JAPP_LAYER_EDITION_TABS[] = [
  JAPP_LAYER_EDITION_TABS.THEMATICS,
  JAPP_LAYER_EDITION_TABS.DYNAMIC_FILTER,
  JAPP_LAYER_EDITION_TABS.GENERAL
]

export const ALL_APP_MESSAGE_SEVERITIES: JAPP_MESSAGE_SEVERITIES[] = [
  JAPP_MESSAGE_SEVERITIES.SUCCESS,
  JAPP_MESSAGE_SEVERITIES.INFO,
  JAPP_MESSAGE_SEVERITIES.WARNING,
  JAPP_MESSAGE_SEVERITIES.ERROR
]

export const ALL_APP_PRINT_FILE_TYPES: JAPP_PRINT_FILE_TYPES[] = [
  JAPP_PRINT_FILE_TYPES.PNG,
  JAPP_PRINT_FILE_TYPES.JPEG,
  JAPP_PRINT_FILE_TYPES.PDF
]

export const ALL_APP_PRINT_PAPER_SIZES: JAPP_PRINT_PAPER_SIZES[] = [
  JAPP_PRINT_PAPER_SIZES.LETTER,
  JAPP_PRINT_PAPER_SIZES.LEGAL,
  JAPP_PRINT_PAPER_SIZES.A3,
  JAPP_PRINT_PAPER_SIZES.A4
]

export const ALL_APP_PRINT_LEGEND_POSITION: JAPP_PRINT_LEGEND_POSITION[] = [
  JAPP_PRINT_LEGEND_POSITION.TOP_RIGHT,
  JAPP_PRINT_LEGEND_POSITION.TOP_LEFT
]

export const ALL_APP_SELECTION_TYPES: JAPP_SELECTION_TYPES[] = [
  JAPP_DRAW_TYPES.POINT,
  JAPP_DRAW_TYPES.LINE_STRING,
  JAPP_DRAW_TYPES.RECTANGLE,
  JAPP_DRAW_TYPES.CIRCLE,
  JAPP_DRAW_TYPES.POLYGON
]

export const ALL_APP_MEASURE_TYPES: JAPP_MEASURE_TYPES[] = [
  JAPP_DRAW_TYPES.POLYGON,
  JAPP_DRAW_TYPES.LINE_STRING,
  JAPP_DRAW_TYPES.CIRCLE
]
